spring:
  application:
    name: phonevip-backend

  config:
    import: classpath:secrets.properties

  datasource:
    url: jdbc:postgresql://localhost:5432/phonevip
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
#      schema-locations: schema.sql
      data-locations: classpath:data.sql

  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
#    uris: http://es:9200 (docker) || http://localhost:9200 (local)
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
