POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=12345678

ELASTICSEARCH_URIS=http://localhost:9200
ELASTICSEARCH_USERNAME=elastic
ELASTICSEARCH_PASSWORD=123456

vnpay.vnp_TmnCode=your_tmn_code # VNPAY merchant code
vnpay.secretKey=your_secret_key # VNPAY secret key

private_origin=your_domain_name # Your domain name (must be https)