POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=12345678

ELASTICSEARCH_URIS=http://localhost:9200
ELASTICSEARCH_USERNAME=elastic
ELASTICSEARCH_PASSWORD=123456

vnpay.vnp_TmnCode=
vnpay.secretKey=

private_origin=